# https://golangci-lint.run/usage/configuration/

run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - gosec
    - govet
    - ifshort
    - makezero
    - misspell
    - nolintlint
    - prealloc
    - unconvert
    - whitespace
