name: Analysis

on:
  pull_request:
    branches:
      - "fix/**"
      - "feature/**"
      - main

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - name: lint
        run: make lint
      - name: test
        run: make test